### ISSUE TITLE
harvest.Harvest() error

### ISSUE THREAD

**Issue by MrJeric0** [lionheart/python-harvest#30]
I get this error when I try to use harvest.Harvest

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lunchbox\Desktop\Dev\PCTEST\EMC-Automation-master\lib\site-packages\harvest\harvest.py", line 55, in __init__
    self.__headers['Authorization'] = 'Basic {0}'.format(enc64('{self.email}:{self.password}'.format(self=self)))
  File "C:\Users\Lunchbox\Desktop\Dev\PCTEST\EMC-Automation-master\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
```

**Comment by Brad-eki** [comment]
Hi @MrJeric0, have you been able to make python-harvest work or is this still a problem?
